version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing Node.js dependencies...
      - npm install
  pre_build:
    commands:
      - echo Pre-build phase...
      # You can add commands here if you need to run something before the build
  build:
    commands:
      - echo Building the React app...
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      # Optional: Add commands to deploy the build artifacts if needed
artifacts:
  files:
    - '**/*'
  base-directory: 'build'
  discard-paths: no
