name: CICD

on:
  push:
    branches:
      - main

# jobs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t dunieskiotano/tekshow-reactjs-app .
      - name: Publish image to docker hub
        run: docker push dunieskiotano/tekshow-reactjs-app:latest   

# deploy
  deploy: 
    needs: build
    runs-on: amazon-ec2    
    steps:
      - name: Pull image from docker hub
        run: docker pull dunieskiotano/tekshow-reactjs-app
      - name: Delete Old Container
        run: docker rm -f reactContainer
      - name: Run docker container
        run: docker run -d -p 3000:80 --name reactContainer dunieskiotano/tekshow-reactjs-app  